### ISSUE TITLE
ember-mocha destroys component before done() is called in integration test

### ISSUE THREAD

**Issue by devinus** [emberjs/ember-mocha#54] opened 2015-08-19 18:53 UTC
```
    it('sets font when a font is selected', function(done) {
      this.render(hbs`{{font-picker value=value}}`);
      Ember.run(this.$('div'), 'click');

      var self = this;
      setTimeout(function() {
        Ember.run($('.fontSelectUl:visible li:first'), 'click');
        console.log('value', self.get('value')); // The component has already been destroyed!
        done();
      }, 250);
    });
```

**Comment by taheilo** [comment] 2015-11-03 13:50
Any solution to this issue?

**Comment by devinus** [comment] 2015-11-03 16:51
@taheilo I have no solution. I think this might be a problem within `ember-mocha` itself.

**Comment by rwjblue** [comment] 2015-11-03 18:16
Can someone provide a reproduction?

**Comment by rwjblue** [comment] 2015-11-03 18:17
You can use http://emberjs.jsbin.com/genolo/edit?html,js as a base for a quick demo, or make an ember-cli app.

**Comment by taheilo** [comment] 2015-11-04 12:19
I've been trying to replicate the scenario (sort of) that im using.

http://emberjs.jsbin.com/tawewokaja/edit?js,console,output

The key is to apparently return the promise. It's still not working in my real setup where the promise comes from a simple auth authentication:

```
var data = {identification: 'password', password: 'password'};
var OAuth2 = application.__container__.lookup('simple-auth-authenticator:oauth2-password-grant');

OAuth2.reopen({
  makeRequest: function(url, data) {
    return this._super(url, data);
  }
});

return currentSession().authenticate('simple-auth-authenticator:oauth2-password-grant', data);
```

I figure it's related to something else in my case; but I'm not quite sure what the issue is yet.

**Comment by Turbo87** [comment] 2016-11-17 21:53
@devinus @taheilo is this still an issue in more recent `ember-mocha` releases?

**Comment by dfalling** [comment] 2017-01-16 22:30
This is still an issue for me.  My integration tests work, but I get a number of errors in my console caused by calling set on a destroyed object.

**Comment by Turbo87** [comment] 2017-01-17 11:18
@dfalling can you provide instructions on how to reproduce this issue?

**Comment by dfalling** [comment] 2017-01-18 05:18
@Turbo87, my mistake- I overlooked one test that I forgot a `wait()` in.  This seems to all be working now!

**Comment by Turbo87** [comment] 2017-01-18 08:21
@dfalling okay, thanks

I'm closing this issue. Please reopen if anyone can come up with a reproduction of the problem.

**Closed by Turbo87** 2017-01-18 08:21 UTC
Labels: bug
