### ISSUE TITLE
seeing obscure errors when trying to update to ember-cli@2.18.0 and ember-mocha 0.12.1 

### ISSUE THREAD

**Issue by efx** [emberjs/ember-mocha#182] opened 2018-01-09 20:51 UTC
It is unclear whether I should post here or ember-cli-mocha, so am posting here.
I'm attempting to upgrade our application to use ember-cli@2.18.0 from ember-cli@2.17.0.
In the process, ember-mocha seems to not work for certain tests.
I see the following error:
<img width="604" alt="screen shot 2018-01-09 at 3 45 03 pm" src="https://user-images.githubusercontent.com/472721/34742448-351137b8-f554-11e7-8ea9-df0a8c023e24.png">. 
I also see an uncaught exception for not loading the `assets/test.js` despite it being loaded.
Here is the relevant snippet from `tests/test-helper.js`:
```js
import Application from 'myapp/app';
import config from '../config/environment';
import resolver from './helpers/resolver';
import { setResolver } from 'ember-mocha';
import { setApplication } from '@ember/test-helpers';

setResolver(resolver);
setApplication(Application.create(config.APP));
mocha.setup({
	timeout: 10000,
	slow: 4000
});

**Comment by rwjblue** [comment] 2018-01-09 21:02
Not sure if it is related, but you generally would not want to do both `setResolver` and `setApplication`...

**Comment by efx** [comment] 2018-01-09 21:03
Ah, thanks @rwjblue. I'll try removing the resolver bit.

**Comment by rstudner** [comment] 2018-01-12 16:52
Hrm.. i'm using Mocha and 2.17 and my test-helper looks like:
```
import resolver from './helpers/resolver';
import { setResolver } from 'ember-mocha';

setResolver(resolver);
```
(which works)

But I did notice going to 2.17.2(?) that there is now some autoboot etc stuff which can't be placed anywhere in the ember-mocha 'setup'

**Comment by Turbo87** [comment] 2018-01-21 13:28
this is a duplicate of https://github.com/ember-cli/ember-cli-mocha/issues/231 and will be addressed by https://github.com/ember-cli/ember-cli-mocha/pull/237

**Closed by Turbo87** 2018-01-21 13:28 UTC
