### ISSUE TITLE
Component Tests Leak Containers

### ISSUE THREAD

**Issue by joegaudet** [emberjs/ember-mocha#167] opened 2017-11-08 17:55 UTC
On Ember Version 2.11.3 and Greater using ember mocha leaks containers between tests.

Steps to Reproduce.

1. Create a vanilla ember app
2. Install ember-cli-mocha
3. Generate 3 component tests
4. Take a heap snapshot and search for containers

<img width="1501" alt="screen shot 2017-11-08 at 9 54 03 am" src="https://user-images.githubusercontent.com/123911/32565080-e93bf504-c46a-11e7-8e81-90051e8aceeb.png">

As you can see there are three containers, and three component tests.

(Will attach a PR shortly)

**Comment by simonihmig** [comment] 2018-02-26 09:40
https://github.com/emberjs/ember-mocha/pull/194 might also have helped here. With that I haven't seen leaks caused by Mocha anymore, so I think we can close this?

**Comment by Turbo87** [comment] 2018-02-26 09:53
@joegaudet can you check if this is still an issue?

**Closed** 2019-05-11 18:06 UTC
